FROM node:22

WORKDIR /app

# 패키지
COPY package*.json ./
COPY pnpm-lock.yaml ./

# pnpm 설치 및 의존성 설치
RUN npm install -g pnpm
RUN pnpm install

# 소스 코드 복사
COPY . .

# typescript 빌드
RUN pnpm run build

# uploads 디렉토리 생성
RUN mkdir -p /app/uploads/posts

# 포트 설정
EXPOSE 4000

CMD ["pnpm", "start"]

