import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./components/ui/Header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Blog",
  description: "Generated by jongsu.jin",
};

export default  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="ko">
       <head>
       <link rel="manifest" href="/manifest.json" />
       <meta name="theme-color" content="#000000" />
       <link rel="apple-touch-icon" href="/icons/test_icon_192x192.png" />
       <meta name="apple-mobile-web-app-status-bar" content="#000000" />
     </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header  />
        {children}
      </body>
    </html>
  );
}
