import type { Metadata } from 'next'
import { Geist, Geist_Mono, JetBrains_Mono } from 'next/font/google'
import './globals.css'
import { Header } from '../shared/component/ui/Header'
import { TanstackProvider } from '@/shared/Provider/TanstackProvider'
// import { HighlightProvider } from '@/shared/Provider/HighlightProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const jetBrainsMono = JetBrains_Mono({
  variable: '--font-jetBrains-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'My Blog',
  description: 'Generated by jongsu.jin',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <TanstackProvider>
      {/* <HighlightProvider> */}
      <html lang="ko">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${jetBrainsMono.variable} antialiased`}
        >
          <Header />
          {children}
        </body>
      </html>
      {/* </HighlightProvider> */}
    </TanstackProvider>
  )
}
